# Generated by Django 5.2 on 2025-04-09 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadedAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='audio/')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('media_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloaded_audio', to='downloader.mediaurl')),
            ],
        ),
    ]
